global:
  scrape_interval:     10s 
  evaluation_interval: 10s 

scrape_configs:
  - job_name: microservice-user
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:7000']
  - job_name: microservice-product
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:7001']
  - job_name: microservice-order
    scrape_interval: 1s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:7002']
      